#ifndef PRIMITIVESDEFINES_H
#define PRIMITIVESDEFINES_H

#define GT_G_PRIMITIVE_BORDER_PEN_WIDTH     1.2
#define GT_G_PRIMITIVE_BORDER_WIDTH         (GT_G_PRIMITIVE_BORDER_PEN_WIDTH * 2)
#define GT_G_PRIVITIVE_BORDER_SPACE_DIVISOR 12.0

#endif // PRIMITIVESDEFINES_H
